[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ytm-album-art-downloader"
version = "0.1.0"
dependencies = ["aiohttp>=3.13.3", "beautifulsoup4", "piexif"]
requires-python = ">=3.12"
authors = [{ name = "Harry Parkes", email = "harrydparkes@proton.me" }]
description = "Scrape album art images from YouTube Music"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["PTH123", "T201", "ANN003", "D100"]
